version: "3.9"
services: 
  web:
    build: .
    image: maalami2020/movieframe:v1
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/movieframe
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mundialmente1
    restart: always
    depends_on:
      - db
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 4200:80
    depends_on:
      - web
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Mundialmente1
      - MYSQL_DATABASE=movieframe
      - MYSQL_PASSWORD=Mundialmente1
    volumes:
      - ./mysql:/var/lib/mysql

