version: "3.9"
services: 
  web:
    image: codeurjc/railway-webapp2-db
    ports:
      - 8443:8443      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/books
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=books
    volumes:
      - ./mysql:/var/lib/mysql