openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8443
  description: Generated server url
paths:
  /api/movies/{id}/edition:
    put:
      tags:
      - movie-rest-controller
      summary: Update movie
      operationId: movieUpdating
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      responses:
        "200":
          description: Updated movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid id supplied
        "404":
          description: No movie with this id was found to update
  /api/users/new:
    post:
      tags:
      - user-rest-controller
      summary: Post user
      operationId: newUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: Posted user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: No user posted
  /api/movies/{id}/review/new:
    post:
      tags:
      - review-rest-controller
      summary: Post review into a movie
      operationId: newReviewAPI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        "400":
          description: Invalid id supplied
        "404":
          description: No movie with this id was found to post a review
        "200":
          description: Posted review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
  /api/movies/addition/new:
    post:
      tags:
      - movie-rest-controller
      summary: Post movie
      operationId: newMovie
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      responses:
        "200":
          description: Posted movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: No movie posted
  /api/movies/addition/new/{id}/image:
    post:
      tags:
      - movie-rest-controller
      summary: Post movie image
      operationId: uploadImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              required:
              - imageFile
              type: object
              properties:
                imageFile:
                  type: string
                  format: binary
      responses:
        "400":
          description: Invalid id supplied
        "404":
          description: No movie with this id was found to post it an image
        "200":
          description: Posted movie image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /api/auth/refresh:
    post:
      tags:
      - login-controller
      operationId: refreshToken
      parameters:
      - name: refreshToken
        in: cookie
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/auth/logout:
    post:
      tags:
      - login-controller
      operationId: logout
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/auth/login:
    post:
      tags:
      - login-controller
      operationId: login
      parameters:
      - name: accessToken
        in: cookie
        required: false
        schema:
          type: string
      - name: refreshToken
        in: cookie
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /userReviewsList/{userName}:
    get:
      tags:
      - user-rest-controller
      operationId: getUserReviews
      parameters:
      - name: userName
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageReview'
  /reviewsList:
    get:
      tags:
      - review-rest-controller
      operationId: getReviews
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageReview'
  /reviewsList/{id}:
    get:
      tags:
      - review-rest-controller
      operationId: deleteReviewById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageReview'
  /reviews/{userName}:
    get:
      tags:
      - review-rest-controller
      operationId: getUserReviews_1
      parameters:
      - name: userName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /movies:
    get:
      tags:
      - movie-rest-controller
      operationId: getMovies
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageMovie'
  /movies/{id}:
    get:
      tags:
      - movie-rest-controller
      operationId: getMovie
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Movie'
  /movies/{id}/image:
    get:
      tags:
      - movie-rest-controller
      operationId: downloadImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /movies/{id}/director/image:
    get:
      tags:
      - movie-rest-controller
      operationId: downloadDirectorImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/usersList:
    get:
      tags:
      - user-rest-controller
      summary: Get users
      operationId: getUsers
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: Found users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: No user founded
  /api/userReviewsList/{userName}:
    get:
      tags:
      - review-rest-controller
      summary: Get the currently logged user reviews
      operationId: getUserReviewsAPI
      parameters:
      - name: userName
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Invalid username supplied
        "404":
          description: No review posted
        "200":
          description: Found user reviews
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
  /api/reviewsList:
    get:
      tags:
      - review-rest-controller
      summary: Get reviews
      operationId: getReviewsAPI
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: Found reviews list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        "404":
          description: No review founded
  /api/reviews/{id}:
    get:
      tags:
      - review-rest-controller
      summary: Get review
      operationId: getReview
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Found review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        "404":
          description: No review with this id was found
        "400":
          description: Invalid id supplied
  /api/movies:
    get:
      tags:
      - movie-rest-controller
      summary: Get movies
      operationId: getMoviesAPI
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "404":
          description: No movie founded
        "200":
          description: Found movies list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /api/movies/{id}:
    get:
      tags:
      - movie-rest-controller
      summary: Get movie
      operationId: getMovieAPI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid id supplied
        "200":
          description: Found movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: No movie with this id was found
  /api/movies/{id}/image:
    get:
      tags:
      - movie-rest-controller
      summary: Get movie image
      operationId: downloadImageAPI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: No movie image with this id was found
        "400":
          description: Invalid id supplied
        "200":
          description: Found movie image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /api/movies/{id}/director/image:
    get:
      tags:
      - director-rest-controller
      summary: Get director image
      operationId: downloadDirectorImageAPI
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: No director image with this id was found
        "400":
          description: Invalid id supplied
        "200":
          description: Found director image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Director'
  /api/movies/name:
    get:
      tags:
      - movie-rest-controller
      summary: Get movies by a name introduced in a dialog box
      operationId: searchMovie
      parameters:
      - name: movie
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Movie'
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: Found movies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: No movie matches this name
  /api/directors/{id}:
    get:
      tags:
      - director-rest-controller
      summary: Get director
      operationId: getDirector
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Found director
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Director'
        "400":
          description: Invalid id supplied
        "404":
          description: No director with this id was found
  /api/Users/current:
    get:
      tags:
      - user-rest-controller
      operationId: getCurrentUser
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /api/reviewsList/{id}:
    delete:
      tags:
      - review-rest-controller
      summary: Delete review
      operationId: deleteReviewById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: No review with this id was found to delete
        "400":
          description: Invalid id supplied
        "200":
          description: Deleted review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
components:
  schemas:
    Director:
      type: object
      properties:
        id:
          type: integer
          format: int64
        director:
          type: string
        biography:
          type: string
        name:
          type: string
        born:
          type: string
        residence:
          type: string
        score:
          type: number
          format: double
        imageFile:
          type: object
          properties:
            binaryStream:
              type: object
        genre:
          type: array
          items:
            type: string
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        image:
          type: boolean
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
        directors:
          type: array
          items:
            $ref: '#/components/schemas/Director'
        description:
          type: string
        imageFile:
          type: object
          properties:
            binaryStream:
              type: object
        category:
          type: string
        votes:
          type: integer
          format: int32
        review:
          $ref: '#/components/schemas/Review'
    Review:
      type: object
      properties:
        id:
          type: integer
          format: int64
        rating:
          type: integer
          format: int32
        coments:
          type: string
        coment:
          type: string
          writeOnly: true
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        name:
          type: string
        email:
          type: string
        roles:
          type: string
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
        mail:
          type: string
          writeOnly: true
        review:
          $ref: '#/components/schemas/Review'
    AuthResponse:
      type: object
      properties:
        status:
          type: string
          enum:
          - SUCCESS
          - FAILURE
        message:
          type: string
        error:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        paged:
          type: boolean
        unpaged:
          type: boolean
        pageSize:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
    Sort:
      type: object
      properties:
        unsorted:
          type: boolean
        sorted:
          type: boolean
        empty:
          type: boolean
    PageReview:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/Review'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        numberOfElements:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        pageable:
          $ref: '#/components/schemas/Pageable'
        empty:
          type: boolean
    PageMovie:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        numberOfElements:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        pageable:
          $ref: '#/components/schemas/Pageable'
        empty:
          type: boolean
