version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: wait-for-it.Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_COLLECTION=posts
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:27017", "--", "node", "src/server.js"]
  db:
    image: mongo:4.4-bionic
    volumes:
      - ./mongo:/data/db